export const data = [
  {
    title: "cs year1-4 focus in AI",
    date: "date 1",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing"],
  },
  {
    title: "cs year1-4 focus in game dev",
    date: "date 1",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing"],
  },
  {
    title: "biomed",
    date: "date 2",
    numLikes: 2,
    numComments: 2,
    username: "thelegend28",
    desc: "this is a description",
    tags: ["science"],
  },
  {
    title: "law kid here",
    date: "date 3",
    numLikes: 3,
    numComments: 3,
    username: "thelegend29",
    desc: "this is a description",
    tags: ["law"],
  },
  {
    title: "archi",
    date: "date 4",
    numLikes: 4,
    numComments: 4,
    username: "thelegend30",
    desc: "this is a description",
    tags: ["design"],
  },
  {
    title: "bba",
    date: "date 5",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["business"],
  },
  {
    title: "fass psych year1-4",
    date: "date 5",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["arts"],
  },
];

// export const faculties = [
//   "Arts and Social Sciences",
//   "computing",
//   "dentistry",
// ];