export const data = [
  {
    id: 0,
    title: "cs year1-4 focus in AI + USP",
    date: "25 Sep 2020",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing", "usp", "single-degree"],
  },
  {
    id: 1,
    title: "cs year1-4 focus in game dev + math 2nd degree",
    date: "6 Nov 2020",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing", "double-degree"],
  },
  {
    id: 2,
    title: "biomed",
    date: "5 Nov 2020",
    numLikes: 2,
    numComments: 2,
    username: "thelegend28",
    desc: "this is a description",
    tags: ["science", "single-degree"],
  },
  {
    id: 3,
    title: "law with exchange to canada",
    date: "2 Nov 2020",
    numLikes: 3,
    numComments: 3,
    username: "thelegend29",
    desc: "this is a description",
    tags: ["law", "single-degree", "sep"],
  },
  {
    id: 4,
    title: "archi",
    date: "1 Nov 2020",
    numLikes: 4,
    numComments: 4,
    username: "thelegend30",
    desc: "this is a description",
    tags: ["design", "single-degree"],
  },
  {
    id: 5,
    title: "bba + noc",
    date: "4 Oct 2020",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["business", "single-degree", "noc"],
  },
  {
    id: 6,
    title: "fass psych year1-4",
    date: "28 Sep 2019",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["arts", "single-degree"],
  },
]

// export const faculties = [
//   "Arts and Social Sciences",
//   "computing",
//   "dentistry",
// ];
