export const data = [
  {
    id: 0,
    title: "cs year1-4 focus in AI + USP",
    date: "25 Sep 2020",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing", "usp", "single-degree"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 1,
      },
    ],
  },
  {
    id: 1,
    title: "cs year1-4 focus in game dev + math 2nd degree",
    date: "6 Nov 2020",
    numLikes: 1,
    numComments: 1,
    username: "thelegend27",
    desc: "this is a description",
    tags: ["computing", "double-degree"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 1,
      },
    ],
  },
  {
    id: 2,
    title: "biomed",
    date: "5 Nov 2020",
    numLikes: 2,
    numComments: 2,
    username: "thelegend28",
    desc: "this is a description",
    tags: ["science", "single-degree"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 1,
      },
    ],
  },
  {
    id: 3,
    title: "law with exchange to canada",
    date: "2 Nov 2020",
    numLikes: 3,
    numComments: 3,
    username: "thelegend29",
    desc: "this is a description",
    tags: ["law", "single-degree", "sep"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 1,
      },
    ],
  },
  {
    id: 4,
    title: "SDE Archi Year 1 - 4 Plan",
    date: "1 Nov 2020",
    numLikes: 4,
    numComments: 2,
    username: "Daniel Lim",
    desc:
      "This is the standard generic plan for archi students. Feel free to reference this and change it according to your own needs and preferences. Hope it would help any year 1's~",
    tags: ["design", "single-degree"],
    comments: [
      {
        username: "JaniceLee",
        date: "3 Nov 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 3,
      },
      {
        username: "Alice Tan",
        date: "4 Nov 2020",
        content: "thank you for this!",
        numLikes: 2,
      },
    ],
  },
  {
    id: 5,
    title: "bba + noc",
    date: "4 Oct 2020",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["business", "single-degree", "noc"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 3,
      },
    ],
  },
  {
    id: 6,
    title: "fass psych year1-4",
    date: "28 Sep 2019",
    numLikes: 5,
    numComments: 5,
    username: "thelegend31",
    desc: "this is a description",
    tags: ["arts", "single-degree"],
    comments: [
      {
        username: "JaniceLee",
        date: "26 sep 2020",
        content: "this was really helpful, thank you!!",
        numLikes: 1,
      },
      {
        username: "Alice Tan",
        date: "28 sep 2020",
        content: "shouldn't CS1231 be in y1s1??",
        numLikes: 1,
      },
    ],
  },
]

// export const faculties = [
//   "Arts and Social Sciences",
//   "computing",
//   "dentistry",
// ];
